FROM node:latest as build-stage
WORKDIR /app
# COPY src/fe_eng/package*.json ./
# RUN npm install
COPY src/fe_eng/ .
# RUN npm run build:sit

FROM nginx
RUN mkdir /app
# COPY --from=build-stage /app/dist /app
COPY src/fe_eng/dist /app
COPY docker/.nginx/nginx.conf /etc/nginx/nginx.conf
